name: "Build Godot 4.2.2 Linux"

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.2.2
          include-templates: true

      - name: Export Linux build
        run: |
          mkdir -p build/linux
          godot --headless --export-release "Linux Universal" build/linux/limbo-linux.x86_64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: limbo-linux-x86_64
          path: build/linux